apiVersion: v1
kind: Service
metadata:
  name: message-server
spec:
  selector:
    app: message-server
  ports:
    - name: grpc-message-server
      protocol: TCP
      port: 9804
      targetPort: 9501
  type: NodePort